version: '3.1'

services:

  db:
    container_name: posgre_livraria
    image: postgres:17.2-alpine

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: posgres_data
    ports:
      - "52:5432"

    restart: always